services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: readeel
      POSTGRES_PASSWORD: "jRIpX1MqCjy8qKhmml3Kk-GZXr-x_1fT"
    volumes:
      - readeel_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "HSCP0KGaBxfA2XdQEkn1U8ryujUcOy51"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: readeel_test
      POSTGRES_PASSWORD: "EYTwk0sIwF9oJN-5NBEFFAYpACK72WY7"
    volumes:
      - readeel_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "tEKMPACvaUOG18sa5-lXgvNqXZ5gUPx_"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  readeel_data:
  readeel_test_data:
